repository: alpha3166/blog
theme: minima
lang: ja-JP
title: アルファのブログ
description: ことば、計算機、SF、ヒコーキ
google_analytics: G-FJ6KMH2L76
plugins:
  - jekyll-sitemap
author: alpha3166
twitter_username: alpha3166
bluesky_username: alpha3166.bsky.social
github_username: alpha3166
timezone: Asia/Tokyo
minima:
  date_format: "%Y-%m-%d"
defaults:
- scope:
    type: posts
  values:
    layout: post
    permalink: /:year:month:day:output_ext
