repository: alpha3166/blog
theme: jekyll-theme-dinky
lang: ja-JP
title: アルファのブログ
description: ことば、計算機、SF、ヒコーキ
github:
  owner_name: alpha3166
  owner_url: https://twitter.com/alpha3166
google_analytics: UA-138711463-1
plugins:
  - jekyll-sitemap
